<?php
return [
    'bucket1' => [
        'id' => 1,
        'name' => 'bucket1',
        'timecreated' => 1600000000,
        'clientid' => 1,
        'archived' => 0,
        'prepaid' => 0,
    ],
    'bucket2' => [
        'id' => 2,
        'name' => 'bucket2',
        'timecreated' => 1600000000,
        'clientid' => 2,
        'archived' => 0,
        'prepaid' => 1,
    ],
    'bucket3' => [
        'id' => 3,
        'name' => 'bucket3',
        'timecreated' => 1600000000,
        'clientid' => 3,
        'archived' => 0,
        'prepaid' => 0,
    ],
    'bucket4' => [
        'id' => 4,
        'name' => 'bucket4',
        'timecreated' => 1600000000,
        'clientid' => 3,
        'archived' => 0,
        'prepaid' => 1,
    ],
    'bucket5' => [
        'id' => 5,
        'name' => 'bucket5',
        'timecreated' => 1600000000,
        'clientid' => 2,
        'archived' => 0,
        'prepaid' => 1,
    ],
    'bucket6' => [
        'id' => 6,
        'name' => 'bucket6',
        'timecreated' => 1600000000,
        'clientid' => 2,
        'archived' => 0,
        'prepaid' => 1,
    ],
    'bucket7' => [
        'id' => 7,
        'name' => 'bucket7',
        'timecreated' => 1600000000,
        'clientid' => 2,
        'archived' => 0,
        'prepaid' => 1,
    ],
];
